version: '3.4'

services:
  database:
    container_name: mysql
    image: mysql:latest
    user: root
    restart: always
    hostname: 'mysql'
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=shopping_cli_test
      - MYSQL_PASSWORD=password
      - MYSQL_USER=testuser 
    ports:
      - 3306:3306
    networks:
      - mynetwork
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      # - C:\Users\yoni golan\Downloads\Docker\Docker\mysql\data:/var/opt/mysql/data
      # - C:\Users\yoni golan\Downloads\Docker\Docker\mysql\log:/var/opt/mysql/log
      # - C:\Users\yoni golan\Downloads\Docker\Docker\mysql\secrets:/var/opt/mysql/secrets
      - ./data.sql:/docker-entrypoint-initdb.d/data.sql
     
  sqlpad:
    container_name: sqlpad
    image: sqlpad/sqlpad:5
    hostname: 'sqlpad'
    ports:
      - '3000:3000'
    networks:
      - mynetwork
    environment:
      SQLPAD_ADMIN: 'admin@sqlpad.com'
      SQLPAD_ADMIN_PASSWORD: 'admin'
      SQLPAD_APP_LOG_LEVEL: info
      SQLPAD_WEB_LOG_LEVEL: warn
      SQLPAD_CONNECTIONS__mysqldemo__name: MySQL Demo
      SQLPAD_CONNECTIONS__mysqldemo__driver: mysql
      SQLPAD_CONNECTIONS__mysqldemo__host: mysql
      SQLPAD_CONNECTIONS__mysqldemo__database: shopping_cli_test
      SQLPAD_CONNECTIONS__mysqldemo__username: testuser
      SQLPAD_CONNECTIONS__mysqldemo__password: password 
    volumes:
      - sqlpad-volume:/var/lib/sqlpad
    depends_on:
      - database

volumes:
  sqlpad-volume:

networks:
  mynetwork:
    driver: bridge
